package org.gradient.waves;

import javax.swing.*;
import java.awt.*;

/**
 * <h1>Waves Panel</h1>
 * WavesPanel is a class extending the JPanel class. Using the Timer class
 * we render different PerlinNoise images, creating animation effect here.
 * @see Timer
 * @see PerlinNoise2D
 */
public class WavesPanel extends JPanel {
    private Timer timer = new Timer(30, e -> repaint());

    private static int gWidth, gHeight, red, green, blue, alpha;

    public WavesPanel(int width, int height, int red, int green, int blue, int alpha){
        timer.start();

        this.gWidth = width;
        this.gHeight = height;
        this.red = red;
        this.green = green;
        this.blue = blue;
        this.alpha = alpha;
    }

    /**
     * <code>paintComponent</code> is the method of <code>JPanel</code>,
     * which is responsible for rendering different noise images,
     * generated by getNoiseImage() method of <code>PerlinNoise2D</code> class through time.
     * @see PerlinNoise2D
     *
     * @param g the <code>Graphics</code> object to protect
     */
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(PerlinNoise2D.getNoiseImage(gWidth, gHeight, red, green, blue, alpha), 0, 0, this);
    }
}
